export default function SpeacerCard() { 
    return(<div style={{margin: 0, blockSize: '479.797px', boxSizing: 'border-box', flexBasis: '33.3333%', flexShrink: 0, fontFamily: 'Proxima Nova, Arial, Helvetica, sans-serif', fontSize: '18px', inlineSize: '390px', lineHeight: '22.5px', maxInlineSize: '33.3333%', minBlockSize: '1px', minHeight: '1px', minInlineSize: 'auto', minWidth: 'auto', paddingBlockEnd: '29px', paddingBottom: '29px', paddingInlineEnd: '15px', paddingInlineStart: '15px', paddingLeft: '15px', paddingRight: '15px', textAlign: 'left', textSizeAdjust: '100%', transitionDuration: '0.3s', transitionProperty: 'opacity', WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)', height: '479.797px'}} className = {"col-6 col-md-4 speakers-card__col  speakers-norris"} data-version = {"version-norris"} >

		<div style={{backgroundColor: 'rgb(255, 255, 255)', blockSize: '450.797px', bottom: '0px', boxShadow: 'rgba(77, 44, 224, 0.3) 0px 3.3345px 25.0088px 0px', boxSizing: 'border-box', cursor: 'pointer', display: 'flex', flexDirection: 'column', fontFamily: 'Proxima Nova, Arial, Helvetica, sans-serif', fontSize: '18px', inlineSize: '360px', insetBlockEnd: '0px', insetBlockStart: '0px', insetInlineEnd: '0px', insetInlineStart: '0px', left: '0px', lineHeight: '22.5px', marginLeft: 0, marginRight: 0, position: 'relative', right: '0px', textAlign: 'left', textSizeAdjust: '100%', top: '0px', transform: 'matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, -1, 0, 0, 0, 1)', transformOrigin: '180px 225.398px', transitionDuration: '0.1s', WebkitBoxOrient: 'vertical', WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)', height: '450.797px'}} href = {"#popup-speakers"} className = {"speakers-card lazy-loaded"} data-options = {{"baseClass": "fancybox-theme-dark"}} data-speaker = {"norris"} >
			<div style={{backgroundImage: 'url(https://synergyglobal.ru/img/speakers/bg-card-2-23f5889a07.jpg)', backgroundPosition: '0px 22px', backgroundRepeat: 'no-repeat', backgroundSize: '100% 100%', blockSize: '251px', bottom: '0px', boxSizing: 'border-box', cursor: 'pointer', fontFamily: 'Proxima Nova, Arial, Helvetica, sans-serif', fontSize: '18px', inlineSize: '360px', insetBlockEnd: '0px', insetBlockStart: '0px', insetInlineEnd: '0px', insetInlineStart: '0px', left: '0px', lineHeight: '22.5px', marginBlockStart: '-22px', marginLeft: 0, marginRight: 0, marginTop: '-22px', minBlockSize: 'auto', minHeight: 'auto', minInlineSize: 'auto', minWidth: 'auto', position: 'relative', right: '0px', textAlign: 'left', textSizeAdjust: '100%', top: '0px', WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)'}} className = {"speakers-card__image speakers-card__image_odd"} >
				<div style={{backgroundColor: 'rgb(184, 0, 248)', blockSize: '38px', borderBlockEndColor: 'rgb(255, 255, 255)', borderBlockStartColor: 'rgb(255, 255, 255)', borderBottomColor: 'rgb(255, 255, 255)', borderInlineEndColor: 'rgb(255, 255, 255)', borderInlineStartColor: 'rgb(255, 255, 255)', borderLeftColor: 'rgb(255, 255, 255)', borderRightColor: 'rgb(255, 255, 255)', borderTopColor: 'rgb(255, 255, 255)', bottom: '0px', boxSizing: 'border-box', caretColor: 'rgb(255, 255, 255)', color: 'rgb(255, 255, 255)', columnRuleColor: 'rgb(255, 255, 255)', cursor: 'pointer', display: 'flex', fontFamily: 'Proxima Nova, Arial, Helvetica, sans-serif', fontSize: '0px', inlineSize: '150px', insetBlockEnd: '0px', insetBlockStart: '213px', insetInlineEnd: '0px', insetInlineStart: '210px', left: '210px', lineHeight: '0px', marginLeft: 0, marginRight: 0, outlineColor: 'rgb(255, 255, 255)', paddingBlockEnd: '11px', paddingBlockStart: '11px', paddingBottom: '11px', paddingInlineEnd: '11px', paddingInlineStart: '11px', paddingLeft: '11px', paddingRight: '11px', paddingTop: '11px', position: 'absolute', right: '0px', textAlign: 'left', textDecoration: 'none solid rgb(255, 255, 255)', textDecorationColor: 'rgb(255, 255, 255)', textEmphasisColor: 'rgb(255, 255, 255)', textSizeAdjust: '100%', textTransform: 'uppercase', top: '213px', WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)', WebkitTextFillColor: 'rgb(255, 255, 255)', WebkitTextStrokeColor: 'rgb(255, 255, 255)'}} className = {"speakers-card__date speakers-card__date_base"} >
									</div>
										<picture style={{blockSize: '251px', boxSizing: 'border-box', cursor: 'pointer', display: 'block', fontFamily: 'Proxima Nova, Arial, Helvetica, sans-serif', fontSize: '18px', inlineSize: '360px', lineHeight: '22.5px', marginLeft: 0, marginRight: 0, maxBlockSize: '251px', maxHeight: '251px', overflowX: 'hidden', overflowY: 'hidden', textAlign: 'left', textSizeAdjust: '100%', WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)'}} >
									<source style={{boxSizing: 'border-box', cursor: 'pointer', fontFamily: 'Proxima Nova, Arial, Helvetica, sans-serif', fontSize: '18px', lineHeight: '22.5px', marginLeft: 0, marginRight: 0, textAlign: 'left', textSizeAdjust: '100%', transitionDuration: '0.1s', WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)'}} type = {"image/png"} className = {"lazy-loaded"} srcset = {'https://synergyglobal.ru/img/speakers/card/norris-69d965e169.png'} ></source>
							<img style={{blockSize: '252px', boxSizing: 'border-box', cursor: 'pointer', fontFamily: 'Proxima Nova, Arial, Helvetica, sans-serif', fontSize: '18px', inlineSize: '360px', lineHeight: '22.5px', marginBlockEnd: '-1px', marginBottom: '-1px', marginLeft: 0, marginRight: 0, maxInlineSize: '100%', maxWidth: '100%', textAlign: 'left', textSizeAdjust: '100%', transitionDuration: '0.1s', verticalAlign: 'middle', WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)', width: '360px', height: '252px'}} className = {"lazy-loaded"} src = {"img/speakers/card/norris-69d965e169.png"} ></img>
	</picture>
								</div>
			<div style={{blockSize: '221.797px', boxSizing: 'border-box', cursor: 'pointer', display: 'flex', flexDirection: 'column', fontFamily: 'Proxima Nova, Arial, Helvetica, sans-serif', fontSize: '18px', inlineSize: '360px', lineHeight: '22.5px', marginLeft: 0, marginRight: 0, minBlockSize: 'auto', minHeight: 'auto', minInlineSize: 'auto', minWidth: 'auto', paddingBlockEnd: '24px', paddingBlockStart: '24px', paddingBottom: '24px', paddingInlineEnd: '24px', paddingInlineStart: '24px', paddingLeft: '24px', paddingRight: '24px', paddingTop: '24px', textAlign: 'left', textSizeAdjust: '100%', WebkitBoxOrient: 'vertical', WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)', height: '221.797px'}} className = {"speakers-card__text"} >
								<div style={{blockSize: '30.7969px', borderBlockEndColor: 'rgb(0, 0, 81)', borderBlockStartColor: 'rgb(0, 0, 81)', borderBottomColor: 'rgb(0, 0, 81)', borderInlineEndColor: 'rgb(0, 0, 81)', borderInlineStartColor: 'rgb(0, 0, 81)', borderLeftColor: 'rgb(0, 0, 81)', borderRightColor: 'rgb(0, 0, 81)', borderTopColor: 'rgb(0, 0, 81)', boxSizing: 'border-box', caretColor: 'rgb(0, 0, 81)', color: 'rgb(0, 0, 81)', columnRuleColor: 'rgb(0, 0, 81)', cursor: 'pointer', fontFamily: 'Proxima Nova Cn, Helvetica Neue, Helvetica, sans-serif', fontSize: '35px', fontWeight: 900, inlineSize: '312px', letterSpacing: '-1.05px', lineHeight: '30.8px', marginBlockEnd: '5px', marginBottom: '5px', marginLeft: 0, marginRight: 0, minBlockSize: 'auto', minHeight: 'auto', minInlineSize: 'auto', minWidth: 'auto', outlineColor: 'rgb(0, 0, 81)', textAlign: 'left', textDecoration: 'none solid rgb(0, 0, 81)', textDecorationColor: 'rgb(0, 0, 81)', textEmphasisColor: 'rgb(0, 0, 81)', textSizeAdjust: '100%', WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)', WebkitTextFillColor: 'rgb(0, 0, 81)', WebkitTextStrokeColor: 'rgb(0, 0, 81)', width: '312px'}} className = {"speakers-card__name condensed"} >Чак Норрис</div>
				<div style={{blockSize: '69px', boxSizing: 'border-box', cursor: 'pointer', fontFamily: 'Proxima Nova, Arial, Helvetica, sans-serif', fontSize: '20px', fontWeight: 600, inlineSize: '312px', lineHeight: '23px', marginLeft: 0, marginRight: 0, minBlockSize: 'auto', minHeight: 'auto', minInlineSize: 'auto', minWidth: 'auto', textAlign: 'left', textSizeAdjust: '100%', WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)'}} className = {"speakers-card__note"} >Голливудский актер кино и телевидения, мастер боевых искусств</div>
				
				
			</div>
		</div>
	</div>
    )
}